apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-self-signed-cert
  namespace: default
spec:
  commonName: my-self-signed-cert
  secretName: my-self-signed-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-self-signed-issuer
